
x-healthcheck-postgres-template: &postgreshealthcheck
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    interval: 30s
    timeout: 10s
    retries: 5

x-healthcheck-redis-template: &redishealthcheck
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 30s
    timeout: 30s
    retries: 3

x-healthcheck-backend: &backendhealthcheck
  healthcheck:
    test: ["CMD", "sh", "-c", "echo 'Checking backend health via /health' && curl -f http://localhost:8000/health || exit 1"]
    interval: 30s
    timeout: 10s
    retries: 5

x-healthcheck-workers: &workershealthcheck
  healthcheck:
      test: ["CMD", "sh", "-c", "ps aux | grep '[p]ython -m workers.scheduler' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

x-healthcheck-nginx: &nginxhealthcheck
  healthcheck:
    test: ["CMD", "nginx", "-t"]
    interval: 30s
    timeout: 10s
    retries: 3

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - assistant-cloud-network
    command: ["./start.sh"]
    <<: *backendhealthcheck

  workers:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workers
    hostname: workers
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - assistant-cloud-network
    restart: unless-stopped
    command: ["python", "-m", "workers.scheduler"]
    <<: *workershealthcheck
    
  postgres:
    image: postgres:17
    container_name: assistant-db
    ports:
      - "5432:5432"
      # - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - assistant-cloud-network
    restart: always
    <<: *postgreshealthcheck

  redis:
    image: redis:alpine3.20
    container_name: redis-server
    restart: always
    expose:
      - "6379"
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - assistant-cloud-network
    command: ["sh", "-c", "redis-server --bind 0.0.0.0 --requirepass $REDIS_PASSWORD"]
    <<: *redishealthcheck

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - assistant-cloud-network
  
networks:
  assistant-cloud-network:
    driver: bridge

volumes:
  postgres_data: